name: catkin build CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:noetic-desktop-full

    steps:
      - uses: actions/checkout@v4
        with:
          path: "src/${{ github.repository_id }}"
      - name: Inspect directory contents
        run: apt-get update && apt-get install --yes tree && pwd && tree
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install build dependencies
        run: apt-get update && apt-get install --yes python3-catkin-tools && python3.10 -m pip install empy
      - name: Run catkin build
        run: . /opt/ros/noetic/setup.sh && catkin build --no-status
      - name: Run yolo checks
        run: poetry run yolo check
        working-directory: "${{ github.workspace }}/src/${{ github.repository_id }}"
